### PR TITLE
fix: Revert "chore: Update dependencies"

### PR DESCRIPTION
**Pull request by addaleax**
This reverts commit b4d3c1a31db29223a18ddaf0bcf4db7ed39c4dea, as it significantly broke the test suite.

### CODE REVIEW

**Comment by jkrems** [comment]
For additional context: Is this about tests running within node's CI, locally, or for travis (or all of them). Asking because "have some kind of CI" is still an open issue for this repo. :(

**Comment by addaleax** [comment]
@jkrems Locally. I thought we had resolved the Travis issue for this org, for the most part? I’ll try to check.

**Comment by jkrems** [comment]
Last time I tried to fix Travis, there seemed to be some builds but they didn’t report to the PRs. I suspect that “delete project on Travis, try from scratch” would be a best strategy at this point.

**Comment by richardlau** [comment]
Maybe switch to GitHub actions for testing?

**Comment by richardlau** [comment]
> 
> 
> Maybe switch to GitHub actions for testing?

I've opened a PR to add testing with GitHub Actions: https://github.com/nodejs/node-inspect/pull/78
It looks like tests are broken with `tap` 14 -- I've dropped back to `tap` 12 in that PR and tests are passing on Node.js 12 and 13 but failing on 10.

**Comment by jkrems** [comment]
It may be worth it to bump the major version and set the minimum version to 12. I don't think we'd back-port `node inspect` changes to node 10 given how infrequently these were in  general.

**Comment by jkrems** [comment]
I'm planning to merge this PR soon since it seems like it brings us closer to stable.  Please protest if that doesn't work for people. :)

**Comment by richardlau** [comment]
I don't think it's necessary to revert the eslint and lint changes but won't stand in the way of this land (those can always be landed again separately without the tap upgrade after the revert).

**Pull request merged**
